"""updating exercise and his sub tables

Revision ID: 2eaf4e3148d1
Revises: 04df9b2c5069
Create Date: 2024-12-28 23:47:34.421700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaf4e3148d1'
down_revision: Union[str, None] = '04df9b2c5069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises_muscles', 'level_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
    
    op.add_column('exercises_muscles', sa.Column('id', sa.Integer(), nullable=False, primary_key=True, autoincrement=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises_muscles', 'level_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('exercises_muscles', 'id')
    # ### end Alembic commands ###
