services:
  # api:
  #   build: .
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_NAME=${DB_NAME}
  #     - API_PORT=${API_PORT}
  #   volumes:
  #     - .:/api
  #   restart: always

  db:
    image: postgres:latest
    container_name: treino_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
