name: Deploy Docker Compose to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1c" # Change to your region
  EC2_IP: "44.212.44.146"
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
  REMOTE_DIR: "/home/deploy/api" # Deployment directory
  API_PORT: "3000" # Default port, adjust as needed
  DB_PORT: "5432"
  SSH_USER: "deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./treino-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Create .env file from GitHub secrets
      - name: Create environment file
        run: |
          cat << EOF > .env
          DB_HOST=db
          DB_PORT=${{ secrets.DB_PORT }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          API_PORT=${{ env.API_PORT }}
          EOF

      # Setup SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host ec2\n  HostName ${{ env.EC2_IP }}\n  User ${{ env.SSH_USER }}\n  IdentityFile ~/.ssh/deploy_key\n  StrictHostKeyChecking no" >> ~/.ssh/config

      # Copy files to EC2
      - name: Copy files via ssh
        run: |
          rsync -avz -e "ssh -i ~/.ssh/deploy_key" \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ ${{ env.SSH_USER }}@${{ env.EC2_IP }}:${{ env.REMOTE_DIR }}

      # Deploy with Docker Compose
      - name: Deploy with Docker Compose
        run: |
          ssh -i ~/.ssh/deploy_key ${{ env.SSH_USER }}@${{ env.EC2_IP }} << 'ENDSSH'
            cd ${{ env.REMOTE_DIR }}
            docker-compose down || true
            docker-compose pull || true
            docker-compose up -d --build
            docker image prune -f
          ENDSSH
