name: Deploy API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/api/treino-legal/treino-api
            if [ ! -f .env ]; then
              echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
              echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
              echo "DB_USER=${{ secrets.DB_USER }}" >> .env
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
              echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
              echo "API_PORT=${{ secrets.API_PORT }}" >> .env
            else
              echo ".env already exists. Skipping..."
            fi
            git pull origin main
            docker-compose down
            docker-compose up -d
