name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./treino-api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Verify SSH Key
        run: |
          ls -la ~/.ssh
          [ -s ~/.ssh/id_rsa ] || exit 1
          echo "SSH key exists and is not empty"

      - name: Deploy via SSH
        run: |
          ssh -v -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            cd /api
            git pull origin main
            docker-compose up -d --build
          EOF
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
